branch-defaults:
  main:
    environment: certus-web-frontend-staging
environment-defaults:
  certus-web-frontend-staging:
    branch: null
    repository: null
global:
  application_name: certus-web
  default_ec2_keyname: certus-web
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
